name: 잡다한 개발 이야기
title: Jake's blog
description: 개발을 하면서 느낀 점을 끄적여 보려 하는 블로그
tags:
  - javascript
  - frontend
  - dev
  - 자바스크립트
  - 프론트엔드
  - 개발
show_hero: true
menu:
  - title: Home
    url: /
  - title: TIL
    url: '/category/til'
  - title: DEV
    url: '/category/dev'
  - title: ABOUT
    url: /about
email: ykwan0714@gmail.com
disqus_username: jake.lim